services:
  reservation_db:
    image: postgres:16
    environment:
      POSTGRES_DB: reservation-service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reservation_db_password
    volumes:
      - reservation_db_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

  fine_db:
    image: postgres:16
    environment:
      POSTGRES_DB: fine_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fine_db_password
    volumes:
      - fine_db_vol:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres

  user_db:
    image: postgres:16
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user_db_password
    volumes:
      - user_db_vol:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - postgres

  book_db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: book
    ports:
      - "5436:5432"
    volumes:
      - bookdb_volume:/var/lib/postgresql/data
    networks:
      - postgres

  loan_db:
    image: postgres:16
    environment:
      POSTGRES_DB: loandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: loan
    ports:
      - "5435:5432"
    volumes:
      - loandb_volume:/var/lib/postgresql/data
    networks:
      - postgres

  notification_db:
    image: postgres:16
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: notification
    ports:
      - "5437:5432"
    volumes:
      - notifdb_volume:/var/lib/postgresql/data
    networks:
      - postgres


  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"   # container içi (PLAINTEXT) - diğer container'lar için
      - "9094:9094"   # host'tan erişim (EXTERNAL)
    environment:
      # KRaft (ZooKeeper yok)
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      # Controller quorum (tek düğüm)
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Listener tanımları
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"

      # Tek kopyalı ayarlar (tek düğüm olduğu için)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_NUM_PARTITIONS: "3"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"

      # Storage / Cluster ID (KRaft için zorunlu)
      # Loglarında gördüğün gibi image CLUSTER_ID bekliyor; güvenli taraf için ikisini de set edelim.
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
      KAFKA_CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"

      # Log dizini (container içi)
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

    volumes: #bilgiler oluşturduğumuz volume'e yazılsın her defasında silinmesin
      - kafka-data:/var/lib/kafka/data
    networks: #oluşturduğumuz networke bağlansın
      - kafkanet

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8079:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092" #kafka-ui, yukarıdaki kafa broker'ına baglanıyor burada
      # İstersen Schema Registry vb. ekleyeceksen aşağıyı kullanırsın:
      # KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"
    networks:
      - kafkanet


volumes:
  reservation_db_vol: {}
  fine_db_vol: {}
  user_db_vol: {}
  kafka-data: {}
  bookdb_volume:
  loandb_volume:
  notifdb_volume:

networks:
  postgres:
  kafkanet: